name: Docker Image CI

on:
  push:
    branches: 
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to Public ECR
      id: login-public-ecr
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_REGION: us-east-1
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag das-s3-fanout-processor:${GITHUB_SHA}
